kind: CertificateSigningRequest
apiVersion: certificates.k8s.io/v1beta1
metadata:
  name: card-csr
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:
    < cat user.csr | base64 | tr -d '\n'> 