kind: ClusterRole
apiVersion: rbac.authroization.k8s.io/v1
metadata:
  name: login-case          # cluster scoped, so not required to mention namespace
spec:
  apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: [get, list, create, delete, update]