apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-1
  labels:
    run: cross
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
            containers:
            - image: busybox
              name: cronbox
              command:
                - sh
                - -c
                - echo "Hello world" > /opt/test.txt
            restartPolicy: OnFailure