kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
data:
  maxmemory: 2mb

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeName: controlplane
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
      volumes:
        - name: data
          emptyDir: {}
        - name: redis-config
          configMap:
              name: redis-config
              items:
                - key: maxmemory
                  path: redis-master
      containers:
        - name: redis-container
          image: redis:alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 1
          volumeMounts:
            - name: data
              mountPath: /redis-master-data
            - name: redis-config
              mountPath: /redis-master
