kind: Deployment
apiVersion: apps/v1
metadata:
  name: destroy
spec:
  replicas: 15
  template:
    metadata:
      name: pod-series
      labels:
        logic: nothing
    spec:
      containers:
        - image: nginx:alpine
          name: alpha-nginx
  selector:
    matchLabels:
      logic: nothing
  strategy:
     type: RollingUpdate
     rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2500               # Get history of rolling update, when upgrading old to new version vice versa
  minReadySeconds: 5

