kind: Deployment
metadata:
  name: host-pod
apiVersion: apps/v1
spec:
  replicas: 5
  selector:
    matchLabels:
      pod: v1
  template:
    metadata:
      name: b1
      labels:
        pod: v1
    spec:
    # When hostNetwork is true then hostPort value must be same with containerPort.
    # hostNetwork: true        # Will not create own Pod IP addr
      containers:
        - image: nginx
          name: testing
          ports:
            - containerPort: 80
              hostPort: 9000           # Will take host system's Port
              protocol: TCP

