kind: Pod                         # resources
apiVersion: v1                    # api group
metadata:                         # contain less but important information about Pod
  name: cluster-policy            # Should be unique | case sensitive 
  labels:                         # useful to detect Pod within cluster
    policy: cluster
spec:                                 # Pod template begins
  containers:                         # pod.spec.containers
    - image: bash                     # image name 
      name: bash-2                    # container name, if other pods has same container name doesn't effect.
      command: ["sleep","4500"]       # command to run as a main process. If we use /bin/sh then shell will execute this process.
  dnsPolicy: ClusterFirst             # policy type is ClusterFirst. Others are: Default | None | ClusterFirstWithHostNet
                                      # We will get inside /etc/resolv.conf, whatever defined in coredns. kubelet does this.
  