apiVersion: v1
kind: Pod
metadata:
  name: downside
  labels:
    run: app
  annotations:
    running-kubernetes.io/pod: downward
    example.io/pod: revision-1
spec:
  containers:
    - image: nginx:1.7.9
      name: downward
      workingDir: /root/
      resources:
        requests:
          cpu: 1
          memory: '500Mi'      # 500Mi --> 500 MebiBytes
        limits:
          cpu: 2             
          memory: '1Gi'
      env:
        - name: NODE_NAME
          valueFrom:               # fieldRef is for Pod Specification
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels
        - name: POD_ANNOTATION
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CONTAINER_MEMORY
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              containerName: downward
        - name: CONTAINER_CPU
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
              containerName: downward
              divisor: 1ki        # 1 KibiByte


