kind: Pod
metadata:
  name: hostaliases
  labels:
    assign: ownhosts
apiVersion: v1
spec:
  containers:
    - image: nginx
      name: manual
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - cat /etc/hosts | tee -a /usr/share/nginx/html/index.html
  hostAliases:       # Can create a hostalias before container start.
  - ip:              # ip and hostnames will be assign for this process.
    - "8.8.8.8"      # string format
    hostnames:
    - "google"
  - ip: 
    - "0.0.0.0"
    hostnames:
    - "welcome"
