kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: hpa-nginx
spec:
  minReplicas: 1
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 20
