kind: Secret
apiVersion: v1
metadata:
  name: myregistrykey
data:
  <encrypted data here>
type: Opaque

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: docker
imagePullSecrets: myregistrykey
