apiVersion: v1
kind: Pod
metadata:
  name: multiple
  labels:
    run: extra
    count: two
spec:
  containers:
    - image: busybox
      name: busybox
      command:
        - "/bin/sh"
        - "-c"
      args: ["cat /opt/open.txt && sleep 5000"]
      volumeMounts:
        - name: vol1
          mountPath: /opt/
  initContainers:
    - image: busybox
      name: init-container
      command:
        - "/bin/sh"
        - "-c"
        - "echo hello world > /opt/open.txt"
      volumeMounts:
        - name: vol1
          mountPath: /opt/
  volumes:
    - name: vol1
      emptyDir: {}

