# Pod updates may not change fields other than below: -
# spec.containers[*].image, spec.initContainers[*].image, spec.activeDeadlineSeconds, spec.tolerations
#

kind: Pod
metadata:
  name: updation
apiVersion: v1
spec:
  terminationGracePeriodSeconds: 30
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
  initContainers:
    - image: busybox:1.28
      name: updater
      command: ["sleep","10"]
