---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  ports:
    - name: test-1
      port: 8080
      targetPort: 8080
      nodePort: 32500
    - name: test-2
      port: 50000
      targetPort: 50000
      nodePort: 31500
  selector:
    app: jenkins

---
kind: Pod
apiVersion: v1
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  volumes:
    - name: data
      emptyDir:
        medium: Memory
        sizeLimit: 1.5Gi
  containers:
    - name: jenkins
      image: jenkins
      workingDir: /var/jenkins_home
      ports:
        - containerPort: 8080
          name: test-1
        - containerPort: 50000
          name: test-2
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: data
          mountPath: /var/jenkins_home/
