---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    app: jenkins

---
apiVersion: apps/v1
metadata:
  name: jenkins-deployment
  namespace: jenkins
  labels:
    app: jenkins
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins-container
          image: jenkins
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        emptyDir: {}