kind: Job
metadata:
  name: task02
  labels:
    app: jobtest
apiVersion: batch/v1
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 1               # In parallel of 1 pod each
  completions: 75              # 75 times will run
  manualSelector: true
  selector:
    matchLabels:
      clock: round
      clock: block
    matchExpressions:
      - key: clock
        operator: In
        values: ["round","block"]
  activeDeadlineSeconds: 20    
  template:
    metadata:
      name: task02
      labels:
        clock: round
        clock: block
    spec:
      restartPolicy: Never
      volumes:
        - name: data
          hostPath:
            path: /opt/
      containers:
        - command: ["/bin/sh","-c"]
          args: 
          - touch /opt/file && echo "Task is only to print message time $(date +%T) and deleted automatically." | tee -a /opt/file
          image: alpine
          name: ola
          volumeMounts:
            - name: data
              mountPath: /opt/

