apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: dock:v1
        name: dock
        ports:
         - containerPort: 4000
        env:
         - name: NAME
           valueFrom:
             configMapKeyRef:
                name: test
                key: name