apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-a
    spec:
      volumeMode: Filesystem
      capacity:
        storage: 100Mi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      nfs:
        path:
        server:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-b
    spec:
      volumeMode: Filesystem
      capacity:
        storage: 100Mi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      nfs:
        path:
        server:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-c
    spec:
      volumeMode: Filesystem
      capacity:
        storage: 100Mi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      nfs:
        path:
        server: