kind: Service
metadata:
  name: web-svc
apiVersion: v1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    stable: v1
---
kind: Deployment
metadata:
  name: app-deploy
  labels:
    run: app-deploy
apiVersion: apps/v1
spec:
  replicas: 2
  selector:
    matchLabels:
      stable: v1
    matchExpression:
      - kind: ver
        operator: In
        values: ["v1"]
  template:
    metadata:
      name: nginx-pod
      labels:
        stable: v1
        ver: v1
    spec:
      volumes:
        - name: log
          hostPath:
            path: /tmp/log
            type: DirectoryOrCreate
        - name: html
          hostPath:
            path: /tmp/html
            type: DirectoryOrCreate
      containers:
          - image: nginx
            name: nginx
            workingDir: /
            volumeMounts:
              - name: log
                mountPath: /var/log
                subPath: log
              - name: html
                mountPath: /usr/share/nginx/html
                subPath: html
          - image: busybox
            name: busy
            volumeMounts:
              - name: log
                mountPath: /tmp/log
                subPath: log
      restartPolicy: Always
