kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: hard
spec:
  podSelector:
    matchLabels:
      version: v1
# By default it will take ingress types
  podTypes:
    - ingress
  ingress:  
  - from:
    - podSelector:
        matchLabels:
          run: nginx
    ports:
      - port: 80
        protocol: TCP