kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-deployment
  labels:
    run: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      tolerations:                         # Schedule Pod on Master Node, without override Taints
        - key: node-role.kubernetes.io/master
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: group                   # Add this label to one of the Node "kubectl label node node-name group=A"
                operator: In
                values: ["A"]
      containers:
      - name: redis-container
        image: redis
