apiVersion: v1
kind: Pod
metadata:
  name: softpod
  labels:
    run: app
spec:
  containers:
    - image: busybox
      name: soft-affinity
      command:
        - "/bin/sh"
        - "-c"
        - "sleep 36000"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: cluster                   
              operator: In                  # If labels is not match, then it will not schedule the pod in the cluster.
              values:                       # Pod status will be in pending state.
              - high
