apiVersion: v1
kind: Pod
metadata:
  name: softpod
  labels:
    run: app
spec:
  containers:
    - image: busybox
      name: soft-affinity
      command:
        - "/bin/sh"
        - "-c"
        - "sleep 36000"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: run                       
                operator: NotIn               # To ignore soft node affinity, then add "NotIn" in operator.
                values:
                - app
