kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-deployment
  labels:
    run: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: group
                operator: In
                values: ["A"]
    containers:
      - name: redis-container
        image: redis
        