apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:               # To bound the PVC to PV via labels, not a good practice.
    matchLabels:
      cap: big
  storageClassName: ""