kind: PersistentVolume
apiVersion: v1
metadata:
  name: pool
  labels:
    cap: big
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""     # empty string helps to choose default storage 
  nfs:
    server:              # Make sure provide appropriate permission in /etc/exportfs -- (rw,no_root_squash) permission issue.
    path: /docker