kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: policy-1
spec:
  runAsUser:
    rule: MustRunAs
    ranges:            # To specify only one specific ID
    - min: 2
      max: 2
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 2
      max: 10
    - min: 60
      max: 100
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 2
      max: 10
    - min: 50
      max: 100
  volumes:
  - emptyDir
  - 
