kind: Pod
apiVersion: v1
metadata:
  name: juice
spec:
  containers:
    - image: alpine
      name: frontside
      command: ["/bin/sleep","4500"]
      securityContext:
        readOnlyRootFilesystem: true            # Makes container's filesystem read-only filesystem
      volumeMounts:                             # Only can edit mounted path volumes file or directory
        - name: volcano
          mountPath: /tmp/logs
        - name: editor
          mountPath: /opt/access.logs
  volumes:
    - name: volcano           # Will create empty directory
      emptyDir: {}
    - name: editor
      hostPath:
        path: /tmp/access.logs              # Will create empty file on schedule host system
        type: FileOrCreate                  