kind: Pod
apiVersion: v1
metadata:
  name: data-fatal
  labels:
    warrior: player
spec:
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: store-pvc
  containers:
    - image: busybox
      name: data
      command: ["sh","-c"]
      args:
        - mkdir /tmp/data-mining;
        - sleep
        - "45000"
      volumeMounts:
        - name: vol1
          mountPath: /tmp/data-mining