apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    run: command-args

spec:
  containers:
    - name: command-args
      image: busybox
      command: ["sleep"]      # In docker it's treated as entrypoint
      args: ["10"]            # In docker it's treated as args
