kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: restrict
spec:
  privileged: false            # container will get rejected if privileged: true
  allowPrivilegeEscalation: false         # non-root + disallow privilege escalation
  requiredDropCapabilities:
    - ALL
  # Volumes allowed
  volumes:
  - configMap
  - secret
  - hostPath
  - persistentVolumeClaim
  - downwardAPI
  - emptyDir
  runAsUser:
    rule: MustRunAsNonRoot
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 2
      max: 10
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 2
      max: 10
  seLinux:
    rule: RunAsAny
  hostNetwork: false
  hostIPC: false
  hostPID: false
  hostPorts:
    - min: 0
      max: 500
  readOnlyRootFilesystem: false


