kind: Pod
apiVersion: v1
metadata:
  name: juice
spec:
  containers:
    - image: alpine
      name: frontside
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: volcano
          mountPath: /tmp/logs
        - name: editor
          mountPath: /opt/access.logs
  volumes:
    - name: volcano
      emptyDir: {}
    - name: editor
      hostPath:
        path: /tmp/logs
        type: FileOrCreate