# Before deploy pod run below command to create a secret.
# kubectl create secret generic token --from-literal=token=xyz123 --from-literal=ticket=redpoint123
# You can create from declarative way as well but prefering imperative way as of now.
---
kind: Pod
metadata:
  name: podinsecret
  labels:
    pod: secret
    value: two
apiVersion: v1
spec:
  containers:
    - image: nginx:alpine
      name: annony
      securityContext:
        allowPrivilegeEscalation: false
      env:
        - name: TOKEN_CODE
          valueFrom:
            secretKeyRef:
              name: token
              key: token
        - name: TICKET_CODE
          valueFrom:
            secretKeyRef:
              name: token
              key: ticket
