---
apiVersion: v1
kind: Namespace
metadata:
  name: fieldref-namespace

---
apiVersion: v1
kind: Pod
metadata:
  name: envars-fieldref
  namespace: fieldref-namespace
spec:
  restartPolicy: Never
  containers:
  - name: fieldref-container
    image: busybox:latest
    command: ['sh','-c']
    args: ["while true; do echo -en '\n'; printenv NODE_NAME POD_NAME POD_NAMESPACE; printenv POD_IP POD_SERVICE_ACCOUN
T; sleep 10; done;"]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
         fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName



