---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-devops
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/dba"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-devops
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-devops
  name: pod-devops
spec:
  volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc-devops
  containers:
  - image: httpd:latest
    name: pod-devops
    volumeMounts:
     - mountPath: "/usr/local/apache2"
       name: storage
---
apiVersion: v1
kind: Service
metadata:
  name: web-devops
spec:
  ports:
  - port: 80
    nodePort: 30008
  selector:
    run: pod-devops
  type: NodePort
