kind: Pod
apiVersion: v1
metadata:
  name: hook
  labels:
    app: hook
spec:
  containers:
    - image: nginx
      name: hook
      env:
        - name: test
          value: "postStart hook testing"
      lifecycle:             # It will not touch main container process and will start immediately when container started.
       postStart:
         exec:                # Available: - exec || tcpSocket || httpGet   
          command:
            - sh
            - -c
            - echo "Hello welcome to $test" > /usr/share/nginx/html/index.html
