kind: PersistentVolume
apiVersion: v1
metadata:
  name: store1
  labels:
    run: store
spec:
  capacity:
    storage: 8G
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  nfs:
    path: /docker
    server: