kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: store-pvc
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5G
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  dataSource:
    name: pvc1
    kind: PersistentVolumeClaim
  
