kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
spec:
  resources:
    requests:
      storage: 2G
  volumeMode: Block    # If we use Block type then kubernetes has to format that device and provide correct Filesystem
  accessModes:              # Match with PV accessModes
    - ReadWriteMany
  storageClassName: "" 
  selector:
    matchLabels:
      name: pv1

# accessModes, and storageClassName is must match with PV --> PVC
#  Under metadata section: Both has own value      
# annotations:
#     pv.kubernetes.io/bind-completed: "yes"
#     pv.kubernetes.io/bound-by-controller: "yes"
# finalizers:     # Same as PV it's extend the immediate deletion  
#   - kubernetes.io/pvc-protection