kind: Pod
apiVersion: v1
metadata:
  name: readinessprobe
  labels:
    app: readinessprobe
spec:
  containers:
    - image: busybox:1.28
      command:
        - sh
        - -c
        - touch /tmp/ready && sleep 4500000000000000000000000000;
      name: test-ready
      readinessProbe:           # readinessProbe test, Periodically it will perform this task.
        exec:
          command:
            - ls
            - /tmp/ready