apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-class
spec:
  hard:
  # Pod count will included with deployments,daemonsets,replicationcontroller,jobs,cronjobs and replicasets  
    pods: "10"         
    requests.cpu: 400m
    requests.memory: 500Mi
    limits.cpu: "1"
    limits.memory: 2Gi
    replicationcontrollers: "3"
    extensions/deployments: "10"
    extensions/daemonsets: "3"
    services: "10"
    services.nodeports: "5"
    services.loadbalancers: "2"
    secrets: "5"
    configmaps: "5"
    requests.storage: 5Gi
    persistentvolumeclaims: "4"
