# secret types : data and stringData
# data secret types supports encoded password.
# echo "secretpassword | base64
# echo "c2VjcmV0cGFzc3dvcmQK" | base64 --decode
# kubectl create secret generic command-password --from-literal=password=mysecretpassword
# echo -n "b3RoZXJwYXNzd29yZAo=" > password.txt
# kubectl create secret generic file-password --from-file=(path/file)password.txt
 
apiVersion: v1
kind: Secret
metadata:
      name: my-password
type: Opaque
data:
  password: c2VjcmV0cGFzc3dvcmQK
---
apiVersion: v1
kind: Secret
metadata:
      name: other-password
type: Opaque
stringData:
     password: secretpassword
# With stringData maps, there is no need to encode the value of each sensitive information field. 
# The value of the sensitive field will be encoded when the `other-password` Secret is created.
    
