kind: Secret
apiVersion: v1
metadata:
  name: beta
type: Generic
data:
  beta.txt: cGFzdGUgeW91ciBlbmNvZGVkIGZpbGUgbmFtZSBoZXJl

---
kind: Pod
apiVersion: v1
metadata:
  name: secret-datacenter
spec:
  containers:
    - name: secret-container-datacenter
      image: fedora:latest
      command: ['/bin/bash','-c','sleep 10000']
      volumeMounts:
        - name: secret-volume-datacenter
          readOnly: true
          mountPath: /opt/cluster
  volumes:
    - name: secret-volume-datacenter
      secret:
        secretName: beta
