kind: Secret
apiVersion: v1
metadata:
  name: db-secret

data:
  DB_Host: c3FsMDE=            # Value in encrypted form, echo -n "<value>" | base64
  DB_User: cm9vdA==            # to decode this value, echo -n "<encrypt value>" | base64 --decode
  DB_Password: cmVkaGF0MTIz