kind: Namespace
apiVersion: v1
metadata:
  name: circle

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: temp-sa
  namespace: circle

---
kind: Pod
metadata:
  name: temp-sa
  namespace: circle
apiVersion: v1
spec:
  volumes:
    - name: data
      emptyDir: {}
  automountServiceAccountToken: false
  serviceAccountName: temp-sa
  containers:
    - image: nginx:alpine
      name: neoma
      ports:
        - containerPort: 80
      volumeMounts:
        - name: data
          mountPath: /tmp
      lifecycle:
        postStart:
          exec:
            command:
            - sh
            - -c
            - echo "Starting time is $(date)" > /tmp/file

