apiVersion: v1
kind: Service
metadata: 
      name: frontend-svc
spec:
    selector:
         app: frontend
    ports:
       - protocol: TCP
         port: 80       # Service port
         targetPort: 8000      # Pod port
