# for a certificate signing reuqest to API
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: <assign encoded value from student.csr>
  usages:
  - digital signature
  - key encipherment
  - client auth
