---
kind: Service
metadata:
  name: nginx-svc
apiVersion: v1
spec:
  clusterIP: None
  ports:
    - port: 9000
      targetPort: 80
  selector:
    static: webapp
---
kind: StatefulSet
metadata:
  name: staticapp
apiVersion: apps/v1
spec:
  replicas: 3
  selector:
    matchLabels:
      static: webapp
  serviceName: nginx-svc
  template:
    metadata:
      name: state-pod
      labels:
        static: webapp
        market: world
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: horo
              mountPath: /opt/data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: horo
      spec:
        resources:
          requests:
            storage: 50Mi
          limits:
            storage: 80Mi
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem