kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user01
  namespace: office
subjects:
- kind: User
  name: user01      # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
 kind: Role         # This must be Role or ClusterRole
 name: user01       # This must be a name of Role or ClusterRole which we created.
 apiGroup: rbac.authorization.k8s.io