kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user01-cluster
# namespace omitted since ClusterRoles are not namespaced
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
